### PR TITLE
Alex chen

### PR DESCRIPTION
**Pull request by zalexchen**
Fixed issue with permissions (See Issues tab)
Created a prototype posting system.

### CODE REVIEW

**Comment by rahulsheth1** [comment]
Great work making a breakthrough in regards to posting! This should help me out with the discussion forum posting, everything looks good.

**Comment by samiachowdhury** [comment]
Thanks, I needed this to finish up the user history page.

**Comment by Sher1nShaj1** [comment]
Awesome work on the profile picture posting.

**Comment by ChloeMJM** [comment]
Tested for api level 30 and 26 and it works great. Nice work.

**Pull request merged**
