### PR TITLE
Added Shared Preferences to SettingsFragment

### PR DESCRIPTION
**Pull request by ChloeMJM**
Added functionality for shared preferences for the settings fragment in regards to user notification preferences. Integrated with Richard's logout functionality so there should be no conflicts.
-Chloe

### CODE REVIEW

**Comment by zalexchen** [comment]
Great work integrating alongside Richard's changes. LGTM.

**Comment by samiachowdhury** [comment]
Everything looks good so far.

**Comment by RichSosa28** [comment]
Tested this file to see how it integrated with my changes and it works smoothly.

**Comment by Sher1nShaj1** [comment]
Looks good. I see no problems.

**Comment by rahulsheth1** [comment]
Looks good, nice update to the settings for the app.

**Pull request merged**
