### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by zalexchen**
Pulling from Dev to Main (Updating Main)

### CODE REVIEW

**Comment by ChloeMJM** [comment]
LGTM! Tested dev branch and it is still running fine, so I don't anticipate any issues with merging to the main branch.

**Comment by Sher1nShaj1** [comment]
Everything seems to be working fine.

**Comment by rahulsheth1** [comment]
Changes look good, thanks for updating main!

**Comment by samiachowdhury** [comment]
I haven't run into any issues. I think we're good to merge.

**Comment by RichSosa28** [comment]
No issues when testing. Ready for merging.

**Pull request merged**
